# syntax = docker/dockerfile:1.2
ARG CONTAINER_OS_DIST=ubuntu

FROM $CONTAINER_OS_DIST:latest as technical-presentation
ARG SECRETS_DIR=""
ARG CONTAINER_OS_DIST

ARG TIME_ZONE="Europe/Zurich"
ARG LOCALE="en_US"

ENV CONTAINER_SETUP_DIR="/container-setup"

ARG USER_NAME="ci"
ARG USER_PASSWORD="$USER_NAME"

ENV CONTAINER_NAME="Technical-Presentation"
ENV CONTAINER_ID="c56dd7b2-7315-478c-820d-33bb6a3dd3cc"
ARG BUILD_VERSION=
ENV CONTAINER_BUILD_VERSION=$BUILD_VERSION
ARG REPOSITORY_COMMIT_SHA
ENV CONTAINER_REPOSITORY_COMMIT_SHA=$REPOSITORY_COMMIT_SHA

ARG USER_UID=1001
ARG USER_GID=1001
ARG LOCAL=en_US
ARG ZSH_HISTORY="/home/$USER_NAME/.zsh_history"
ARG PYTHON_ENVS="/home/$USER_NAME/python-envs"
ARG INSTALL_MAN_PAGES=false

# Basics just until we have Nix.
RUN if [ "$INSTALL_MAN_PAGES" = "true" ]; then yes | unminimize ; fi
RUN apt update && \
  apt install -y \
  systemd \
  sudo \
  bash \
  curl \
  git \
  zsh \
  xz-utils \
  tzdata \
  ca-certificates && \
  update-ca-certificates

# Add common scripts.
COPY devcontainer/setup/common $CONTAINER_SETUP_DIR/common

# Set the locale.
COPY devcontainer/setup/setup-locales.sh $CONTAINER_SETUP_DIR/
RUN chmod +x $CONTAINER_SETUP_DIR/setup-locales.sh && \
  $CONTAINER_SETUP_DIR/setup-locales.sh --locale "$LOCALE"
ENV LANG $LOCALE.UTF-8
ENV LC_ALL $LOCALE.UTF-8
ENV LANGUAGE $LOCALE.UTF-8

# Configure Timezone.
COPY devcontainer/setup/setup-time-zone.sh $CONTAINER_SETUP_DIR/
RUN chmod +x $CONTAINER_SETUP_DIR/setup-time-zone.sh && \
  $CONTAINER_SETUP_DIR/setup-time-zone.sh \
  --time-zone "$TIME_ZONE"

# Add the user.
COPY devcontainer/setup/setup-user.sh $CONTAINER_SETUP_DIR/
RUN chmod +x $CONTAINER_SETUP_DIR/setup-user.sh && \
  $CONTAINER_SETUP_DIR/setup-user.sh "$USER_NAME" "$USER_UID" "$USER_GID"
USER "$USER_NAME"
ENV USER="$USER_NAME"

# Setup Nix.
COPY --chown=$USER_NAME:$USER_NAME devcontainer/setup/setup-nix.sh $CONTAINER_SETUP_DIR/
RUN chmod +x $CONTAINER_SETUP_DIR/setup-nix.sh && \
  $CONTAINER_SETUP_DIR/setup-nix.sh
ENV PATH="/home/$USER_NAME/.nix-profile/bin:$PATH"

# Install dependencies.
COPY ./ "$CONTAINER_SETUP_DIR/tools/nix"/
RUN cd "$CONTAINER_SETUP_DIR" && git init && git add . && \
  git -c user.name="CI" -c user.email="ci@ci.com" commit -a -m "init"
RUN cd "$CONTAINER_SETUP_DIR" && \
  nix develop --no-pure-eval "./tools/nix#default" --command true && \
  nix store gc

# Add ZSH shell and plugins.
COPY --chown=$USER_NAME:$USER_NAME devcontainer/setup/setup-zsh.sh $CONTAINER_SETUP_DIR/
COPY --chown=$USER_NAME:$USER_NAME devcontainer/setup/shell $CONTAINER_SETUP_DIR/shell/
RUN chmod +x $CONTAINER_SETUP_DIR/setup-zsh.sh && \
  $CONTAINER_SETUP_DIR/setup-zsh.sh "$PATH"

# Setup runtime script
COPY --chown=$USER_NAME:$USER_NAME devcontainer/setup/setup-runtime.sh $CONTAINER_SETUP_DIR/
RUN chmod +x $CONTAINER_SETUP_DIR/setup-runtime.sh

WORKDIR "/home/$USER_NAME"
ENTRYPOINT ["/container-setup/setup-runtime.sh"]

CMD ["zsh"]
